### ISSUE TITLE
Useless installation guides for conda env

### ISSUE THREAD

**Issue by KornbergFresnel** [PettingZoo-Team/AutoROM#5]
**Environment**

- Ubuntu 20.04
- Conda python3.7.9
- pip==21.0.1

**ISSUE**

Installed `autorom` but raised an error:

```bash
raise IOError(f"rom {game} is not installed. Please install roms using AutoROM tool 
(https://github.com/PettingZoo-Team/AutoROM) "
OSError: rom boxing is not installed. Please install roms using AutoROM tool (
https://github.com/PettingZoo-Team/AutoROM) or specify and double-check 
the path to your Atari rom using the `rom_path` argument.
```

**Where is AutoRom installed**: `miniconda3/envs/workspace/lib/python3.7/site-packages/AutoROM/` (and there are no binary files).

**Expected**: `miniconda3/envs/workspace/lib/python3.7/site-packages/multi_agent_ale_py/ROM/{game}/{game.bin}`

**Comment by RyanNavillus** [comment]
Thank you for raising this issue. I'll look into this more in a bit, but it seems to be an issue with the released version on PyPI. I was able to install the ROMs to the correct location by cloning this repo and running that version of AutoROM. Let me know if that solves your problem. If not, could you provide the command line output from AutoROM, including the directory that it is supposedly saving the ROMs to?

**Comment by RyanNavillus** [comment]
After investigating a bit more, it's possible that when you use AutoROM, it's calling the system version rather than the conda version. One possible solution to this is to uninstall AutoROM from the system-wide site-packages, and just install it in your conda env.

```
conda deactivate
pip uninstall AutoROM
conda activate myenv
pip install AutoROM
```

If you run AutoROM after this, you should see that the directory it lists for installing ROMs is your current conda environments site-packages folder, rather than the system-wide one. Note that you may also need to install multi_agent_ale_py to this conda environment for it to show the correct directory.

**Comment by KornbergFresnel** [comment]
> After investigating a bit more, it's possible that when you use AutoROM, it's calling the system version rather than the conda version. One possible solution to this is to uninstall AutoROM from the system-wide site-packages, and just install it in your conda env.
> 
> ```
> conda deactivate
> pip uninstall AutoROM
> conda activate myenv
> pip install AutoROM
> ```
> 
> If you run AutoROM after this, you should see that the directory it lists for installing ROMs is your current conda environments site-packages folder, rather than the system-wide one. Note that you may also need to install multi_agent_ale_py to this conda environment for it to show the correct directory.

I updated the description, my AutoROM (and `multi_agent_ale_py`) locates in conda environment, not system-wide.

**Comment by RyanNavillus** [comment]
Could you run the `AutoROM` command in your terminal and provide the output from that command? You'll need to run the command to install the ROM files, and when you do, it should tell you where it's planning to install the files.

**Comment by KornbergFresnel** [comment]
@RyanNavillus oh, sorry for the late reply, I've addressed this issue with your guides. :)
